### ISSUE TITLE
address 0.6 warnings + drop 0.5

### ISSUE THREAD

**Issue by CarloLucibello** [CarloLucibello/FatGraphs.jl#44]
- [x] Erdos.jl already addressed in #43 
- [x] Clustering.jl's ones here JuliaStats/Clustering.jl#82
- [ ] ParserCombinator.jl first attempt here andrewcooke/ParserCombinator.jl#21

TODO: As soon as 0.6 is out, drop julia 0.5 support and make use of  0.6 syntax (e.g. `where`).
People on 0.5 will use last 0.5-compatible tagged version

**Comment by CarloLucibello** [comment]
0.6 warnings addressed in #73
